## This has been replaced by nginx-proxy-manager - keeping here just for reference
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:1.7
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
     # - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:ro
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    networks:
      - proxy_network

networks:
  proxy_network:
    name: proxy_network
    driver: bridge
