services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      DOMAIN: "https://vw.domain.tld"
    volumes:
      - ./data/:/data/
    ports:
      - 8070:80
    networks:
      - vaultwarden_network
      - proxy_network

networks:
  proxy_network:
    external: true
  vaultwarden_network:
    name: vaultwarden_network
    driver: bridge
