services:
  protonmail-bridge:
    container_name: proton-bridge
    image: shenxn/protonmail-bridge:latest
    ports:
      - 1025:25/tcp
      - 1143:143/tcp
    restart: unless-stopped
    volumes:
      - protonmail:/root
    networks:
      - mail-net
volumes:
  protonmail:
    external: true

networks:
    mail-net:
      external: true
