services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: "1000:1000"
    networks:
      - jellyfin_network
      - proxy_network
    volumes:
      - /jellyfin/config:/config
      - /jellyfin/cache:/cache
      - type: bind
        source: /home/cjski/Downloads/qbittorrent/movies
        target: /media/movies
      - type: bind
        source: /home/cjski/Downloads/qbittorrent/series
        target: /media/series
      - type: bind
        source: /path/to/fonts
        target: /usr/local/share/fonts/custom
        read_only: true
    restart: 'unless-stopped'
    environment:
      - JELLYFIN_PublishedServerUrl=http://jellyfin.local
    extra_hosts:
      - 'host.docker.internal:host-gateway'

networks:
  proxy_network:
    external: true
  jellyfin_network:
    name: jellyfin_network
    driver: bridge